### PR TITLE
added .travis.yml file

### PR DESCRIPTION
**Pull request by djacobs74**
added this file per Travis CI instructions

### CODE REVIEW

**Comment by lasley** [comment]
Failing at db https://travis-ci.org/it-is-5pm-somwhere/team-chess-app/jobs/159393343#L297

**Comment by djacobs74** [comment]
I thought all we needed to do was create a local DB like we did for the
other Firehose apps. I am so confused by Travis CI, there are only 3 steps
at https://travis-ci.org/getting_started

**Comment by lasley** [comment]
I recommend you look deeper into the docs, such as the one for Ruby - https://docs.travis-ci.com/user/languages/ruby

**Comment by lasley** [comment]
@djacobs74  http://www.yamllint.com/

**Comment by djacobs74** [comment]
@lasley got this to pass on http://www.yamllint.com/    

--- 
? "-before_script"
: "bundle exec rake db:drop db:create db:migrate"
? "-script"
: "bundle exec rspec spec/"
language: ruby
rvm: "2.3.0"

**Pull request closed without merging**
