### PR TITLE
Test code factories

### PR DESCRIPTION
**Pull request by mbrown78**
create test code factories for user, player, game and piece. Added has_one :player association to user. 

Dependent on:

- [x] #3

### CODE REVIEW

**Comment by lasley** [comment]
LGTM - I set to work in progress and noted dependency in initial comment. Will re-review once dependency is merged.

**Comment by lasley** [comment]
@mbrown78 - you will need to rebase onto current master in order to get rid of the commits that have been merged. Here is the process:
```
git checkout master
git pull
git checkout my_branch
git checkout -b backup/my_branch
git checkout my_branch
git rebase master
git push -f
```

Note in the above we created a backup branch because we are performing a dangerous operation - rewriting history. Any time you have to `git push -f` you know it's dangerous.

Once I take a look at the outcome of what you have done, you can delete the backup branch from your local if you care.

**Comment by saakuffo** [comment]
@lasley wait, hold on now. I think I missed something. Why are we rebasing?

**Comment by lasley** [comment]
@saakuffo This PR includes commits that are already on master - 0d8c739, 6e4fc4d. Merging as is will duplicate the commits. Rebasing will replay the commits on top of the current master, and git will realize the two are identical. The will then be removed from the changeset and things will be much cleaner.

**Comment by lasley** [comment]
Although now that the conflict is here, the rebase is going to be a bitch. Better solution:

```
git checkout master
git pull
git checkout my_branch
git checkout -b backup/my_branch
git checkout my_branch
git reset --hard origin/master
git cherry-pick 6531a5b
```

Resolve conflicts, commit like normal to finish the cherry pick

**Comment by saakuffo** [comment]
Hey @mbrown78. we made a ton of changes to base master and made sure it had your model. please pull new master and branch off that to integrate your factories.

**Pull request closed without merging**
